version: "3.5"

services:
    backend: 
        container_name: unsplash-backend
        build: ./backend
        volumes:
          - /app/node_modules
          - ./backend:/app
        ports: 
            - 5000:5000
    frontend:
        container_name: unsplash-frontend
        build: ./frontend
        volumes:
          - /app/frontend/node_modules
          - ./frontend:/app/frontend
        ports:
            - 3000:3000