version: "3.9"

services:
    backend: 
        container_name: unsplash-backend
        build: 
            context: ./backend
        volumes:
          - ./backend:/app
          - node_modules:/app/node_modules
        ports: 
            - "5000:5000"
        environment:
            - CHOKIDAR_USEPOLLING=true
    frontend:
        container_name: unsplash-frontend
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - react_node_modules:/app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        # tty: true
        # stdin_open: true
volumes:
    react_node_modules:
    node_modules: